name: Checkmarx AST Scan - on Push
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: cx_gs_enablement
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
