# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  push_event:
    name: pushevent
    if: github.event_name == 'push'
    uses: jvlstuff/JavaVulnerableLab/.github/workflows/gh-bugtrack-cxflow.yml@master
    with:
        bugtracker: GitHub
        branch: ${{github.ref}}
    secrets:
        sast_username: ${{ secrets.CX_PRIVATECLOUD_USERNAME }}
        sast_password: ${{ secrets.CX_PRIVATECLOUD_PASSWORD }}
        sca_username: ${{ secrets.CXSCA_USERNAME }}
        sca_password: ${{ secrets.CXSCA_PASSWORD }}
        
  pull_request:
      name: pullrequest
      if: github.event_name == 'pull_request'
      uses: jvlstuff/JavaVulnerableLab/.github/workflows/gh-bugtrack-cxflow.yml@master
      with:
        bugtracker: GITHUBPULL
        branch: ${{github.head_ref}}
      secrets:
        sast_username: ${{ secrets.CX_PRIVATECLOUD_USERNAME }}
        sast_password: ${{ secrets.CX_PRIVATECLOUD_PASSWORD }}
        sca_username: ${{ secrets.CXSCA_USERNAME }}
        sca_password: ${{ secrets.CXSCA_PASSWORD }}
   
